# Generated by Django 3.0.8 on 2020-09-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200907_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='trump',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
