# Generated by Django 3.0.8 on 2020-09-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200907_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='trump',
        ),
        migrations.RemoveField(
            model_name='player',
            name='cards',
        ),
    ]
