# Generated by Django 3.0.8 on 2020-09-11 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20200908_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='attacker_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chat',
            name='winner',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=240)),
                ('value', models.CharField(db_index=True, max_length=240)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Chat')),
            ],
        ),
    ]
