# Generated by Django 3.0.8 on 2020-09-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200911_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='winner',
            field=models.CharField(default=None, max_length=1),
        ),
    ]
